name: linux
on: 
  workflow_dispatch:
defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run config
      env: # Or as an environment variable
        EMAIL: ${{ secrets.EMAIL }}
      run: source script-linux.sh
#    - name: Setup tmate session
#      uses: mxschmitt/action-tmate@master
#     - run: gh repo clone $GITHUB_REPOSITORY -- --depth 1
    - uses: lhotari/action-upterm@v1

